#!/usr/bin/env python3
"""gen-zone-contract.py — emit the sources for the zone-contract
libsystem_malloc replacement.

The full pin-faithful rebuild fights the SDK/clang header web (see the
control #15 doc); this generator takes the narrow path the dispatch
allows: a dylib at the SAME install name that (a) exports the original's
full symbol set (stubs for the unused ones), (b) provides a bump
allocator behind malloc/free/calloc/realloc so the guest keeps running,
and (c) returns a zone object laid out per the macOS-13 contract the
chrome framework dispatches through (slot0=size, slot3=destroy — control
#14 measured the overlay's slots as reserved/reserved/size/malloc/...).

Usage: gen-zone-contract.py <nm-gU-dump> <out-dir>
Writes: zone-contract.c (the real bodies + the zone object) and
zone-stubs.s (the remaining exports), plus exports.txt.
"""
import subprocess
import sys


def main():
    dump_path, out = sys.argv[1], sys.argv[2]
    names = []
    seen = set()
    for line in open(dump_path):
        parts = line.split()
        if len(parts) >= 3 and parts[2] not in seen:
            # nm -gU on a fat dylib prints each export once per slice;
            # keep the first occurrence only
            seen.add(parts[2])
            names.append((parts[1], parts[2]))  # (type, symbol)
    real_text = {
        "_malloc", "_free", "_calloc", "_realloc", "_valloc",
        "_malloc_default_zone", "_malloc_get_all_zones",
        "_malloc_default_purgeable_zone", "_malloc_zone_malloc",
        "_malloc_zone_free", "_malloc_zone_realloc", "_malloc_zone_size",
        "_malloc_create_zone", "_malloc_set_zone_name",
    }
    stubs = []
    for t, name in names:
        if name in real_text:
            continue
        stubs.append((t, name))
    with open(f"{out}/exports.txt", "w") as f:
        f.write("\n".join(n for _t, n in names) + "\n")
    with open(f"{out}/zone-stubs.s", "w") as f:
        f.write("# generated by gen-zone-contract.py — non-core exports\n")
        for t, name in names:
            if name in real_text:
                continue
            if t in ("D", "d", "B", "b", "S", "s", "C"):
                f.write(f".data\n.globl {name}\n{name}:\n    .quad 0\n")
            else:
                f.write(f".text\n.globl {name}\n{name}:\n    xorl %eax, %eax\n    ret\n")
    print(f"exports: {len(names)}; real bodies: {len(real_text & {n for _t, n in names})}; stubs: {len(stubs)}")


if __name__ == "__main__":
    main()
