#!/bin/sh
# Build darlingserver on FreeBSD 15.1 (standalone, without full Darling cmake tree).
# Run on the build VM: sh /path/to/darling/build-freebsd/build-darlingserver.sh
# Requires: pkg install cmake llvm epoll-shim

set -e

BUILD=/var/darling-build/dserver
DS=/path/to/darling/src/external/darlingserver
SRC=/path/to/darling/src
COMPAT=${SRC}/startup/compat-includes

rm -rf "${BUILD}" && mkdir -p "${BUILD}" && cd "${BUILD}"

# rtsig.h is normally generated by the startup/rtsig binary
printf '#define LINUX_SIGRTMIN %d\n#define LINUX_SIGRTMAX %d\n' 65 126 > rtsig.h

cat > CMakeLists.txt << 'CMEOF'
cmake_minimum_required(VERSION 3.13)
project(darlingserver CXX C)

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}   -std=gnu11  -ggdb -O0")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17  -ggdb -O0")

set(DS   /path/to/darling/src/external/darlingserver)
set(SRC  /path/to/darling/src)
set(DRPC ${DS}/generated-rpc)
set(COMPAT /path/to/darling/src/startup/compat-includes)

set(CMAKE_INSTALL_PREFIX "/usr/local")
set(CMAKE_INSTALL_LIBDIR "lib")
set(SUFFIX "")
set(GIT_BRANCH "pr-arm64")
set(GIT_COMMIT_HASH "freebsd-port")
configure_file(
  ${SRC}/include/darling-config.h.in
  ${CMAKE_BINARY_DIR}/darling-config.h
)

include_directories(
  ${COMPAT}
  /usr/local/include/libepoll-shim
  ${DS}/include
  ${DS}/internal-include
  ${DS}/duct-tape/include
  ${DRPC}/include
  ${DRPC}/internal-include
  ${SRC}/libsimple/include
  ${CMAKE_BINARY_DIR}
)

add_definitions(
  -D_GNU_SOURCE
  -DDARLING_FREEBSD
  -DLIBSIMPLE_FREEBSD=1
  -DDSERVER_SINGLE_THREADED=1
)

# Support library: libsimple lock + FreeBSD POSIX compat (eventfd, timerfd) + dtape stubs
add_library(simple STATIC
  ${SRC}/libsimple/src/lock.c
  ${SRC}/startup/bsdos_posix_compat.c
  ${SRC}/startup/dtape_stubs.c
)
target_include_directories(simple PUBLIC
  ${SRC}/libsimple/include
  ${COMPAT}
)
target_compile_definitions(simple PUBLIC LIBSIMPLE_FREEBSD=1)

set(DS_SRCS
  ${DS}/src/utility.cpp
  ${DS}/src/registry.cpp
  ${DS}/src/darlingserver.cpp
  ${DS}/src/message.cpp
  ${DS}/src/server.cpp
  ${DS}/src/process.cpp
  ${DS}/src/thread.cpp
  ${DS}/src/logging.cpp
  ${DS}/src/call.cpp
  ${DS}/src/async-writer.cpp
  ${DS}/src/kqchan.cpp
  ${DS}/src/stack-pool.cpp
)

add_executable(darlingserver ${DS_SRCS})
target_link_libraries(darlingserver simple -L/usr/local/lib -lepoll-shim -lutil -ljail -lpthread)
CMEOF

cmake .
make -j$(sysctl -n hw.ncpu)
echo "=== Built: ${BUILD}/darlingserver ==="
ls -lh "${BUILD}/darlingserver"
