#!/bin/sh
# Build darlingserver on FreeBSD 15.1 (standalone, without full Darling cmake tree).
# Run on the build VM: sh /path/to/darling/build-freebsd/build-darlingserver.sh
# Requires: pkg install cmake llvm epoll-shim

set -e

BUILD=/var/darling-build/dserver
DS=/path/to/darling/src/external/darlingserver
SRC=/path/to/darling/src
COMPAT=${SRC}/startup/compat-includes

rm -rf "${BUILD}" && mkdir -p "${BUILD}" && cd "${BUILD}"

# rtsig.h is normally generated by the startup/rtsig binary
printf '#define LINUX_SIGRTMIN %d\n#define LINUX_SIGRTMAX %d\n' 65 126 > rtsig.h

cat > CMakeLists.txt << 'CMEOF'
cmake_minimum_required(VERSION 3.13)
project(darlingserver CXX C)

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}   -std=gnu11  -ggdb -O0")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17  -ggdb -O0")

set(DS   /path/to/darling/src/external/darlingserver)
set(SRC  /path/to/darling/src)
set(DRPC ${DS}/generated-rpc)
set(COMPAT /path/to/darling/src/startup/compat-includes)

set(CMAKE_INSTALL_PREFIX "/usr/local")
set(CMAKE_INSTALL_LIBDIR "lib")
set(SUFFIX "")
set(GIT_BRANCH "pr-arm64")
set(GIT_COMMIT_HASH "freebsd-port")
configure_file(
  ${SRC}/include/darling-config.h.in
  ${CMAKE_BINARY_DIR}/darling-config.h
)

include_directories(
  ${COMPAT}
  /usr/local/include/libepoll-shim
  ${DS}/include
  ${DS}/internal-include
  ${DS}/duct-tape/include
  ${DRPC}/include
  ${DRPC}/internal-include
  ${SRC}/libsimple/include
  ${CMAKE_BINARY_DIR}
)

add_definitions(
  -D_GNU_SOURCE
  -DDARLING_FREEBSD
  -DLIBSIMPLE_FREEBSD=1
  -DDSERVER_SINGLE_THREADED=1
)

# Support library: libsimple lock + FreeBSD POSIX compat (eventfd, timerfd)
add_library(simple STATIC
  ${SRC}/libsimple/src/lock.c
  ${SRC}/startup/bsdos_posix_compat.c
)
target_include_directories(simple PUBLIC
  ${SRC}/libsimple/include
  ${COMPAT}
)
target_compile_definitions(simple PUBLIC LIBSIMPLE_FREEBSD=1)

# Prebuilt duct-tape (real XNU Mach IPC emulation, replaces dtape_stubs.c)
add_library(dtape STATIC IMPORTED)
set_target_properties(dtape PROPERTIES
  IMPORTED_LOCATION /var/darling-build/dtape/dtape-build/libdtape.a
)

set(DS_SRCS
  ${DS}/src/utility.cpp
  ${DS}/src/registry.cpp
  ${DS}/src/darlingserver.cpp
  ${DS}/src/message.cpp
  ${DS}/src/server.cpp
  ${DS}/src/process.cpp
  ${DS}/src/thread.cpp
  ${DS}/src/logging.cpp
  ${DS}/src/call.cpp
  ${DS}/src/async-writer.cpp
  ${DS}/src/kqchan.cpp
  ${DS}/src/stack-pool.cpp
)

add_executable(darlingserver ${DS_SRCS})
target_link_libraries(darlingserver simple dtape -L/usr/local/lib -lepoll-shim -lutil -ljail -lpthread -lc++)
CMEOF

cmake .
make -j$(sysctl -n hw.ncpu)
echo "=== Built: ${BUILD}/darlingserver ==="
ls -lh "${BUILD}/darlingserver"

# ── Build real mldr ───────────────────────────────────────────────────────────
MLDR_REAL_BUILD="${BUILD}/mldr-real"
rm -rf "${MLDR_REAL_BUILD}" && mkdir -p "${MLDR_REAL_BUILD}" && cd "${MLDR_REAL_BUILD}"

cat > CMakeLists.txt << 'MLDR_CMEOF'
cmake_minimum_required(VERSION 3.13)
project(mldr_real C)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=gnu11 -ggdb -O2")

set(SRC  /path/to/darling/src)
set(DS   /path/to/darling/src/external/darlingserver)
set(DRPC ${DS}/generated-rpc)

include_directories(
  ${SRC}/startup/mldr/include
  ${SRC}/startup/mldr
  ${SRC}/external/cctools-port/cctools/include
  ${DRPC}/include
  ${DS}/include
)

add_definitions(
  -DDARLING_FREEBSD
  -D_GNU_SOURCE
  -DINSTALL_PREFIX=\"/usr/local/darling-overlay\"
  -DSYSTEM_ROOT=\"/Volumes/SystemRoot\"
  -DLIBEXEC_PATH=\"/usr/local/darling-overlay/libexec/darling\"
)

# mldr sources (mldr.c includes loader.c and stack.c at the end, so only add these two)
add_executable(mldr
  ${SRC}/startup/mldr/mldr.c
  ${SRC}/startup/mldr/commpage.c
)

target_link_libraries(mldr PRIVATE -lc -lpthread)
MLDR_CMEOF

cmake .
make -j$(sysctl -n hw.ncpu)
echo "=== Built: ${MLDR_REAL_BUILD}/mldr (real) ==="
ls -lh "${MLDR_REAL_BUILD}/mldr"

# Install real mldr to replace stub
MLDR_DEST="/usr/local/libexec/darling/usr/libexec/darling/mldr"
mkdir -p "$(dirname ${MLDR_DEST})"
install -m 755 "${MLDR_REAL_BUILD}/mldr" "${MLDR_DEST}"
echo "=== Installed: ${MLDR_DEST} (real mldr) ==="
ls -lh "${MLDR_DEST}"
