#!/bin/sh
# Build darlingserver on FreeBSD 15.1 (standalone, without full Darling cmake tree).
# Usage: sh build-freebsd/build-darlingserver.sh
# Requires: pkg install cmake llvm epoll-shim
#
# Environment:
#   DARLING_BUILD_DIR  — where build artefacts go (default: /tmp/darling-build)
#   DARLING_SRC_DIR    — root of this repository  (default: directory of this script/..)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="${DARLING_BUILD_DIR:-/var/darling-build}/dserver"
DS="${DARLING_SRC_DIR:-${SCRIPT_DIR}}/src/external/darlingserver"
SRC="${DARLING_SRC_DIR:-${SCRIPT_DIR}}/src"
COMPAT="${SRC}/startup/compat-includes"
DTAPE_LIB="${DARLING_BUILD_DIR:-/var/darling-build}/dtape/dtape-build/libdtape.a"

rm -rf "${BUILD}" && mkdir -p "${BUILD}" && cd "${BUILD}"

# rtsig.h is normally generated by the startup/rtsig binary
printf '#define LINUX_SIGRTMIN %d\n#define LINUX_SIGRTMAX %d\n' 65 126 > rtsig.h

cat > CMakeLists.txt << CMEOF
cmake_minimum_required(VERSION 3.13)
project(darlingserver CXX C)

set(CMAKE_C_FLAGS   "\${CMAKE_C_FLAGS}   -std=gnu11  -ggdb -O0")
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -std=c++17  -ggdb -O0")

set(DS   ${DS})
set(SRC  ${SRC})
set(DRPC \${DS}/generated-rpc)
set(COMPAT ${COMPAT})

set(CMAKE_INSTALL_PREFIX "/usr/local")
set(CMAKE_INSTALL_LIBDIR "lib")
set(SUFFIX "")
set(GIT_BRANCH "pr-arm64")
set(GIT_COMMIT_HASH "freebsd-port")
configure_file(
  \${SRC}/include/darling-config.h.in
  \${CMAKE_BINARY_DIR}/darling-config.h
)

include_directories(
  \${COMPAT}
  /usr/local/include/libepoll-shim
  \${DS}/include
  \${DS}/internal-include
  \${DS}/duct-tape/include
  \${DRPC}/include
  \${DRPC}/internal-include
  \${SRC}/libsimple/include
  \${CMAKE_BINARY_DIR}
)

add_definitions(
  -D_GNU_SOURCE
  -DDARLING_FREEBSD
  -DLIBSIMPLE_FREEBSD=1
  -DDSERVER_SINGLE_THREADED=1
)

# Support library: libsimple lock + FreeBSD POSIX compat (eventfd, timerfd)
add_library(simple STATIC
  \${SRC}/libsimple/src/lock.c
  \${SRC}/startup/bsdos_posix_compat.c
)
target_include_directories(simple PUBLIC
  \${SRC}/libsimple/include
  \${COMPAT}
)
target_compile_definitions(simple PUBLIC LIBSIMPLE_FREEBSD=1)

# Prebuilt duct-tape (real XNU Mach IPC emulation, replaces dtape_stubs.c)
add_library(dtape STATIC IMPORTED)
set_target_properties(dtape PROPERTIES
  IMPORTED_LOCATION ${DTAPE_LIB}
)

set(DS_SRCS
  \${DS}/src/utility.cpp
  \${DS}/src/registry.cpp
  \${DS}/src/darlingserver.cpp
  \${DS}/src/message.cpp
  \${DS}/src/server.cpp
  \${DS}/src/process.cpp
  \${DS}/src/thread.cpp
  \${DS}/src/logging.cpp
  \${DS}/src/call.cpp
  \${DS}/src/async-writer.cpp
  \${DS}/src/kqchan.cpp
  \${DS}/src/stack-pool.cpp
)

add_executable(darlingserver \${DS_SRCS})
target_link_libraries(darlingserver simple dtape -L/usr/local/lib -lepoll-shim -lutil -ljail -lpthread -lc++)
CMEOF

cmake .
make -j$(sysctl -n hw.ncpu)
echo "=== Built: ${BUILD}/darlingserver ==="
ls -lh "${BUILD}/darlingserver"

# mldr is built separately by build-mldr-only.sh (the complete recipe: includes
# freebsd_syscall_trap.c, elfcalls.c, threads.c and generates darling-config.h).
# This script used to also build an mldr here, but that copy predated
# freebsd_syscall_trap.c and had drifted into a stale, incomplete duplicate
# that `rm -rf`'d and clobbered build-mldr-only.sh's output. Removed — run
# build-mldr-only.sh after this script instead.
