#!/usr/bin/env python3
"""gen-cg-supl.py — emit a stub .s for a provider supplement dylib.

Reads the missing-symbol list (one symbol per line, from
sym-wall-map.py / chrome-imports-by-ordinal.py --missing) and writes an
assembly file: kCG*/kCM* constants -> 8-byte zero data objects;
everything else -> a text stub (xor eax,eax; ret). Types follow the symbol
name, which matches the overlay stubs' own convention (their kCG* constants
are data).

Usage: gen-cg-supl.py <missing.txt> <out.s> [install_name]
The optional install_name (default /usr/lib/suppl.dylib) is echoed in the
header and in the link recipe printed after generation.
"""
import sys

DATA_PREFIXES = ("_kCG", "_kCM", "_kCA", "_kCV", "_kCI", "_kMT",
                 "_OBJC_CLASS_", "_OBJC_METACLASS_", "___")
DEF_INSTALL = "/usr/lib/suppl.dylib"


def main():
    src, dst = sys.argv[1], sys.argv[2]
    install = sys.argv[3] if len(sys.argv) > 3 else DEF_INSTALL
    names = [l.strip() for l in open(src) if l.strip()]
    out = [f"# generated by gen-cg-supl.py — supplement stubs for {install}",
           ".text"]
    n_text = n_data = 0
    for name in names:
        if name.startswith(DATA_PREFIXES):
            out += [f".data", f".globl {name}", f"{name}:", ".quad 0"]
            n_data += 1
        else:
            out += [f".text", f".globl {name}", f"{name}:",
                    "    xorl %eax, %eax", "    ret"]
            n_text += 1
    open(dst, "w").write("\n".join(out) + "\n")
    print(f"wrote {dst}: {n_text} text stubs, {n_data} data stubs, {len(names)} total")
    print("link recipe:")
    print(f"  clang -target x86_64-apple-macos10.12 -c {dst} -o {dst}.o")
    print(f"  ld64.lld -dylib -arch x86_64 -platform_version macos 10.12 10.12 \\")
    print(f"    -install_name {install} -current_version 1.0.0 \\")
    print(f"    -compatibility_version 1.0.0 -o {dst}.dylib {dst}.o")


if __name__ == "__main__":
    main()
