#!/usr/bin/env python3
"""gen-cg-supl.py — emit a stub .s for the CoreGraphics supplement dylib.

Reads the missing-symbol list (one symbol per line, from
chrome-imports-by-ordinal.py --missing) and writes an assembly file:
kCG*/kCM* constants -> 8-byte zero data objects; everything else -> a
text stub (xor eax,eax; ret). Types follow the symbol name, which matches
the overlay stub's own convention (its kCGColorSpace* are data).

Usage: gen-cg-supl.py <missing.txt> <out.s>
"""
import sys

DATA_PREFIXES = ("_kCG", "_kCM", "_kCA", "_kCV", "_kCI", "_kMT")


def main():
    src, dst = sys.argv[1], sys.argv[2]
    names = [l.strip() for l in open(src) if l.strip()]
    out = ["# generated by gen-cg-supl.py — CoreGraphics supplement stubs",
           ".text"]
    n_text = n_data = 0
    for name in names:
        if name.startswith(DATA_PREFIXES):
            out += [f".data", f".globl {name}", f"{name}:", ".quad 0"]
            n_data += 1
        else:
            out += [f".text", f".globl {name}", f"{name}:",
                    "    xorl %eax, %eax", "    ret"]
            n_text += 1
    open(dst, "w").write("\n".join(out) + "\n")
    print(f"wrote {dst}: {n_text} text stubs, {n_data} data stubs, {len(names)} total")


if __name__ == "__main__":
    main()
