/*
 * hello-cf.c — minimal CoreFoundation program.
 *
 * purpose:     Prove the loader can run code through the REAL
 *              CoreFoundation.framework (CFAllocator, CFString creation,
 *              length query, and conversion back to a C string) — the
 *              layer directly beneath Foundation/Cocoa, which this overlay
 *              does not carry at all (only CoreFoundation.framework,
 *              DirectoryService.framework, LDAP.framework and
 *              SystemConfiguration.framework are present).
 * input:       None.
 * output:      "hello-cf: HELLO CF (len 8)\n" on stdout.
 * sideEffects: None.
 *
 * Build: see build-freebsd/build-real-macho-tests.sh.
 */
/* Individual headers, not the <CoreFoundation/CoreFoundation.h> umbrella:
 * the vendored darling-corefoundation submodule ships CoreFoundation.h as a
 * symlink to include/CoreFoundation/CoreFoundation.h, but that target
 * doesn't actually exist in the checkout (presumably generated by a build
 * step this repo's CMakeLists doesn't expose standalone) — same class of
 * gap as the SDK's own broken/missing symlinks (see tests/vendor/README.md). */
#include <CoreFoundation/CFBase.h>
#include <CoreFoundation/CFString.h>

extern int printf(const char *, ...);

int main(void) {
    CFStringRef s = CFStringCreateWithCString(kCFAllocatorDefault, "hello cf",
                                               kCFStringEncodingUTF8);
    CFMutableStringRef upper = CFStringCreateMutableCopy(kCFAllocatorDefault, 0, s);
    CFStringUppercase(upper, NULL);

    CFIndex len = CFStringGetLength(upper);
    char buf[64] = {0};
    CFStringGetCString(upper, buf, sizeof(buf), kCFStringEncodingUTF8);

    printf("hello-cf: %s (len %ld)\n", buf, (long)len);

    CFRelease(upper);
    CFRelease(s);
    return 0;
}
